Simplify usage by updating to new default loop
reactphp/website pull request #54
Opened 2021-07-10 08:09 UTC by clue

This changeset simplifies usage by updating to use the new [default loop](https://github.com/reactphp/event-loop#loop).

Builds on top of https://github.com/reactphp/event-loop/pull/226, https://github.com/reactphp/event-loop/pull/232, https://github.com/reactphp/socket/pull/260 and https://github.com/reactphp/http/pull/410

2021-07-10 08:14 UTC, clue commented
This is ready for review. I can merge once reviewed and the linked components have been tagged.

2021-07-10 10:11 UTC, jsor approved these changes

2021-07-10 11:28 UTC, WyriHaximus requested changes

2021-07-10 11:28 UTC, WyriHaximus commented on theme/homepage.html.twig
> +$socket = new React\Socket\Server('127.0.0.1:8080');
Might as well make it listen on all IP's

```suggestion
$socket = new React\Socket\Server('0.0.0.0:8080');
```

2021-07-10 16:42 UTC, clue commented on theme/homepage.html.twig
> +$socket = new React\Socket\Server('127.0.0.1:8080');
No strong preference here tbh. I think recommending localhost listen address as a starting point is a more safe. Exposing this to the public internet requires only slightly more effort, but this is where things start to highly depend on use case / setup anyway, such as reverse proxy etc.. Additionally, the localhost address can also be used as is in URLs, which might make getting started slightly easier. WDYT?

2021-07-11 13:32 UTC, WyriHaximus approved these changes

2021-07-11 13:32 UTC, merged

2021-07-11 14:24 UTC, WyriHaximus commented on theme/homepage.html.twig
> +$socket = new React\Socket\Server('127.0.0.1:8080');
True, but IMHO we could better educate what values are often used in production. Any machine you startup should have a firewall enabled by default. I agree that it's safer, but we should also guide our users from start to production with our project and these little things help.